/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import models.User;

/**
 *
 * @author Fiqih
 */
public class PemesananFrame extends javax.swing.JFrame {

    
    private User userAktif;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PemesananFrame.class.getName());

    /**
     * Creates new form PemesananFrame
     */
    public PemesananFrame() {
        initComponents();
    }
    
    public PemesananFrame(User user) {
        initComponents();
        this.userAktif = user; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblMenuMakanan = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMenuMinuman = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKeranjangMakanan = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblKeranjangMinuman = new javax.swing.JTable();
        pnlSidebar = new javax.swing.JPanel();
        lblKohiSop = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnOrder = new javax.swing.JButton();
        btnMember = new javax.swing.JButton();
        btnKitchen = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        pnlHeader = new javax.swing.JPanel();
        lblMenuOrder = new javax.swing.JLabel();
        pnlMakananMenu = new javax.swing.JPanel();
        lblMakananMenu = new javax.swing.JLabel();
        pnlMinumanMenu = new javax.swing.JPanel();
        lblMinumanMenu = new javax.swing.JLabel();
        pnlTambahKeranjang1 = new javax.swing.JPanel();
        lblTambahKeranjang = new javax.swing.JLabel();
        pnlTambahKeranjang = new javax.swing.JPanel();
        lblKode = new javax.swing.JLabel();
        txtKodeMenu = new javax.swing.JTextField();
        lblKuantitas = new javax.swing.JLabel();
        txtKuantitas = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        pnlMakananKeranjang = new javax.swing.JPanel();
        lblMakananKeranjang = new javax.swing.JLabel();
        pnlMinumanKeranjang = new javax.swing.JPanel();
        lblMinumanKeranjang = new javax.swing.JLabel();
        pnlTotal = new javax.swing.JPanel();
        btnBatal = new javax.swing.JButton();
        btnSelesai = new javax.swing.JButton();
        lblTotalHarga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblMenuMakanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Harga"
            }
        ));
        tblMenuMakanan.setToolTipText("");
        jScrollPane3.setViewportView(tblMenuMakanan);
        if (tblMenuMakanan.getColumnModel().getColumnCount() > 0) {
            tblMenuMakanan.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblMenuMakanan.getColumnModel().getColumn(1).setPreferredWidth(250);
            tblMenuMakanan.getColumnModel().getColumn(2).setPreferredWidth(70);
        }

        tblMenuMinuman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Harga"
            }
        ));
        jScrollPane4.setViewportView(tblMenuMinuman);
        if (tblMenuMinuman.getColumnModel().getColumnCount() > 0) {
            tblMenuMinuman.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblMenuMinuman.getColumnModel().getColumn(1).setPreferredWidth(250);
            tblMenuMinuman.getColumnModel().getColumn(2).setPreferredWidth(70);
        }

        tblKeranjangMakanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Harga", "Qty", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblKeranjangMakanan);
        if (tblKeranjangMakanan.getColumnModel().getColumnCount() > 0) {
            tblKeranjangMakanan.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblKeranjangMakanan.getColumnModel().getColumn(1).setPreferredWidth(250);
            tblKeranjangMakanan.getColumnModel().getColumn(2).setPreferredWidth(70);
            tblKeranjangMakanan.getColumnModel().getColumn(3).setPreferredWidth(40);
            tblKeranjangMakanan.getColumnModel().getColumn(4).setPreferredWidth(80);
        }

        tblKeranjangMinuman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Harga", "Qty", "Subtotal"
            }
        ));
        jScrollPane5.setViewportView(tblKeranjangMinuman);
        if (tblKeranjangMinuman.getColumnModel().getColumnCount() > 0) {
            tblKeranjangMinuman.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblKeranjangMinuman.getColumnModel().getColumn(1).setPreferredWidth(250);
            tblKeranjangMinuman.getColumnModel().getColumn(2).setPreferredWidth(70);
            tblKeranjangMinuman.getColumnModel().getColumn(3).setPreferredWidth(40);
            tblKeranjangMinuman.getColumnModel().getColumn(4).setPreferredWidth(80);
        }

        pnlSidebar.setBackground(new java.awt.Color(0, 102, 102));

        lblKohiSop.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lblKohiSop.setForeground(new java.awt.Color(255, 255, 255));
        lblKohiSop.setText("KohiSop");

        btnOrder.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnOrder.setText("Order");
        btnOrder.addActionListener(this::btnOrderActionPerformed);

        btnMember.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnMember.setText("Member");

        btnKitchen.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnKitchen.setText("Kitchen");

        btnLogout.setBackground(new java.awt.Color(255, 51, 51));
        btnLogout.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout pnlSidebarLayout = new javax.swing.GroupLayout(pnlSidebar);
        pnlSidebar.setLayout(pnlSidebarLayout);
        pnlSidebarLayout.setHorizontalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSidebarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSidebarLayout.createSequentialGroup()
                        .addGroup(pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnOrder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMember, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(btnKitchen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSidebarLayout.createSequentialGroup()
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSidebarLayout.createSequentialGroup()
                        .addComponent(lblKohiSop)
                        .addGap(55, 55, 55))))
        );
        pnlSidebarLayout.setVerticalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblKohiSop)
                .addGap(68, 68, 68)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnMember, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnKitchen, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));

        lblMenuOrder.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMenuOrder.setForeground(new java.awt.Color(0, 102, 102));
        lblMenuOrder.setText("Menu & Order");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblMenuOrder)
                .addContainerGap(623, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblMenuOrder)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pnlMakananMenu.setBackground(new java.awt.Color(0, 102, 102));

        lblMakananMenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblMakananMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblMakananMenu.setText("Makanan");

        javax.swing.GroupLayout pnlMakananMenuLayout = new javax.swing.GroupLayout(pnlMakananMenu);
        pnlMakananMenu.setLayout(pnlMakananMenuLayout);
        pnlMakananMenuLayout.setHorizontalGroup(
            pnlMakananMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMakananMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMakananMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMakananMenuLayout.setVerticalGroup(
            pnlMakananMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMakananMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMakananMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMinumanMenu.setBackground(new java.awt.Color(0, 102, 102));
        pnlMinumanMenu.setPreferredSize(new java.awt.Dimension(65, 28));

        lblMinumanMenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblMinumanMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblMinumanMenu.setText("Minuman");

        javax.swing.GroupLayout pnlMinumanMenuLayout = new javax.swing.GroupLayout(pnlMinumanMenu);
        pnlMinumanMenu.setLayout(pnlMinumanMenuLayout);
        pnlMinumanMenuLayout.setHorizontalGroup(
            pnlMinumanMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMinumanMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMinumanMenu)
                .addContainerGap(317, Short.MAX_VALUE))
        );
        pnlMinumanMenuLayout.setVerticalGroup(
            pnlMinumanMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMinumanMenuLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(lblMinumanMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pnlTambahKeranjang1.setBackground(new java.awt.Color(0, 102, 102));

        lblTambahKeranjang.setBackground(new java.awt.Color(255, 255, 255));
        lblTambahKeranjang.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTambahKeranjang.setForeground(new java.awt.Color(255, 255, 255));
        lblTambahKeranjang.setText("Tambah ke Keranjang");

        javax.swing.GroupLayout pnlTambahKeranjang1Layout = new javax.swing.GroupLayout(pnlTambahKeranjang1);
        pnlTambahKeranjang1.setLayout(pnlTambahKeranjang1Layout);
        pnlTambahKeranjang1Layout.setHorizontalGroup(
            pnlTambahKeranjang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTambahKeranjang1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTambahKeranjang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTambahKeranjang1Layout.setVerticalGroup(
            pnlTambahKeranjang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTambahKeranjang1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTambahKeranjang)
                .addContainerGap())
        );

        pnlTambahKeranjang.setBackground(new java.awt.Color(255, 255, 255));

        lblKode.setText("Kode");

        txtKodeMenu.addActionListener(this::txtKodeMenuActionPerformed);

        lblKuantitas.setText("Kuantitas");

        btnTambah.setBackground(new java.awt.Color(0, 204, 204));
        btnTambah.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        javax.swing.GroupLayout pnlTambahKeranjangLayout = new javax.swing.GroupLayout(pnlTambahKeranjang);
        pnlTambahKeranjang.setLayout(pnlTambahKeranjangLayout);
        pnlTambahKeranjangLayout.setHorizontalGroup(
            pnlTambahKeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTambahKeranjangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTambahKeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKode, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKodeMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pnlTambahKeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTambahKeranjangLayout.createSequentialGroup()
                        .addComponent(txtKuantitas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTambah))
                    .addComponent(lblKuantitas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTambahKeranjangLayout.setVerticalGroup(
            pnlTambahKeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTambahKeranjangLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlTambahKeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKode)
                    .addComponent(lblKuantitas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTambahKeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKuantitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKodeMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlMakananKeranjang.setBackground(new java.awt.Color(0, 102, 102));

        lblMakananKeranjang.setBackground(new java.awt.Color(0, 102, 102));
        lblMakananKeranjang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMakananKeranjang.setForeground(new java.awt.Color(255, 255, 255));
        lblMakananKeranjang.setText("Makanan");

        javax.swing.GroupLayout pnlMakananKeranjangLayout = new javax.swing.GroupLayout(pnlMakananKeranjang);
        pnlMakananKeranjang.setLayout(pnlMakananKeranjangLayout);
        pnlMakananKeranjangLayout.setHorizontalGroup(
            pnlMakananKeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMakananKeranjangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMakananKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMakananKeranjangLayout.setVerticalGroup(
            pnlMakananKeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMakananKeranjangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMakananKeranjang)
                .addContainerGap())
        );

        pnlMinumanKeranjang.setBackground(new java.awt.Color(0, 102, 102));

        lblMinumanKeranjang.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblMinumanKeranjang.setForeground(new java.awt.Color(255, 255, 255));
        lblMinumanKeranjang.setText("Minuman");

        javax.swing.GroupLayout pnlMinumanKeranjangLayout = new javax.swing.GroupLayout(pnlMinumanKeranjang);
        pnlMinumanKeranjang.setLayout(pnlMinumanKeranjangLayout);
        pnlMinumanKeranjangLayout.setHorizontalGroup(
            pnlMinumanKeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMinumanKeranjangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMinumanKeranjang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMinumanKeranjangLayout.setVerticalGroup(
            pnlMinumanKeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMinumanKeranjangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMinumanKeranjang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTotal.setBackground(new java.awt.Color(255, 255, 255));

        btnBatal.setBackground(new java.awt.Color(255, 51, 51));
        btnBatal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("Batalkan");

        btnSelesai.setBackground(new java.awt.Color(102, 255, 102));
        btnSelesai.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSelesai.setText("Selesai & Lanjut Pembayaran");
        btnSelesai.addActionListener(this::btnSelesaiActionPerformed);

        lblTotalHarga.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTotalHarga.setForeground(new java.awt.Color(0, 102, 102));
        lblTotalHarga.setText("Total Harga : Rp 0");

        javax.swing.GroupLayout pnlTotalLayout = new javax.swing.GroupLayout(pnlTotal);
        pnlTotal.setLayout(pnlTotalLayout);
        pnlTotalLayout.setHorizontalGroup(
            pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTotalLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBatal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSelesai)
                .addGap(18, 18, 18))
        );
        pnlTotalLayout.setVerticalGroup(
            pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTotalLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalHarga))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                                .addComponent(pnlMakananMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(pnlMinumanMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pnlTambahKeranjang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(pnlTambahKeranjang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlMakananKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pnlMinumanKeranjang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlTambahKeranjang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMakananMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlTambahKeranjang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlMakananKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlMinumanKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(pnlMinumanMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(134, 134, 134)
                .addComponent(pnlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnlSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKodeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeMenuActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        
        int pilihan = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Apakah kamu yakin ingin keluar dari akun?", 
            "Konfirmasi Logout", 
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE);

        if (pilihan == javax.swing.JOptionPane.YES_OPTION) {
            this.userAktif = null; 

            new LoginFrame().setVisible(true);

            this.dispose();
        }
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                models.MenuModel menuModel = new models.MenuModel();
//                models.PemesananModel pesanModel = new models.PemesananModel(menuModel);
//                
//                views.PemesananFrame view = new views.PemesananFrame();
//                
//                new controllers.PemesananController(menuModel, pesanModel, view, user);
//                
//                view.setLocationRelativeTo(null);
//                view.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnKitchen;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMember;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JButton btnTambah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblKode;
    private javax.swing.JLabel lblKohiSop;
    private javax.swing.JLabel lblKuantitas;
    private javax.swing.JLabel lblMakananKeranjang;
    private javax.swing.JLabel lblMakananMenu;
    private javax.swing.JLabel lblMenuOrder;
    private javax.swing.JLabel lblMinumanKeranjang;
    private javax.swing.JLabel lblMinumanMenu;
    private javax.swing.JLabel lblTambahKeranjang;
    private javax.swing.JLabel lblTotalHarga;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMakananKeranjang;
    private javax.swing.JPanel pnlMakananMenu;
    private javax.swing.JPanel pnlMinumanKeranjang;
    private javax.swing.JPanel pnlMinumanMenu;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JPanel pnlTambahKeranjang;
    private javax.swing.JPanel pnlTambahKeranjang1;
    private javax.swing.JPanel pnlTotal;
    private javax.swing.JTable tblKeranjangMakanan;
    private javax.swing.JTable tblKeranjangMinuman;
    private javax.swing.JTable tblMenuMakanan;
    private javax.swing.JTable tblMenuMinuman;
    private javax.swing.JTextField txtKodeMenu;
    private javax.swing.JTextField txtKuantitas;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnBatal() {
        return btnBatal;
    }

    public JButton getBtnTambah() {
        return btnTambah;
    }

    public JTextField getTxtKodeMenu() {
        return txtKodeMenu;
    }

    public JTextField getTxtKuantitas() {
        return txtKuantitas;
    }

    public JButton getBtnSelesai() {
        return btnSelesai;
    }

    public JTable getTblKeranjangMakanan() {
        return tblKeranjangMakanan;
    }

    public JTable getTblKeranjangMinuman() {
        return tblKeranjangMinuman;
    }

    public JTable getTblMenuMakanan() {
        return tblMenuMakanan;
    }

    public JTable getTblMenuMinuman() {
        return tblMenuMinuman;
    }

    public JLabel getLblTotalHarga() {
        return lblTotalHarga;
    }

    public JButton getBtnLogout() {
        return btnLogout;
    }

    public JButton getBtnKitchen() {
        return btnKitchen;
    }

}
